;
CREATE USER IF NOT EXISTS ADMIN SALT 'af20e8ec611d8aab' HASH '9bc4f547e973527e5df74e46b5cb149141f2aa45718a1ff60b4ad5a8de0edcd4' ADMIN;
CREATE CACHED TABLE PUBLIC.EVALUATION(
                                         ID VARCHAR(255) NOT NULL,
                                         COMMENT VARCHAR(255),
                                         DATE TIMESTAMP,
                                         GRADE DECIMAL(19, 2),
                                         POINTS DECIMAL(19, 2),
                                         VERSION BIGINT,
                                         EXAM_ID VARCHAR(255),
                                         PARTICIPANTSTATUS_ID VARCHAR(255),
                                         SUBMISSION_ID VARCHAR(255),
                                         TASK_ID VARCHAR(255),
                                         USER_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.EVALUATION ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVALUATION;
CREATE CACHED TABLE PUBLIC.EXAM(
                                   ID VARCHAR(255) NOT NULL,
                                   DATE TIMESTAMP,
                                   LOCATION VARCHAR(255),
                                   NAME VARCHAR(255),
                                   VERSION BIGINT,
                                   WEIGHTING DECIMAL(19, 2),
                                   MEETING_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.EXAM ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EXAM;
CREATE CACHED TABLE PUBLIC.FINALGRADE(
                                         ID VARCHAR(255) NOT NULL,
                                         OVERALLGRADE DECIMAL(19, 2),
                                         PASSED BOOLEAN,
                                         SUBMISSIONGRADE DECIMAL(19, 2),
                                         VERSION BIGINT,
                                         MEETING_ID VARCHAR(255),
                                         PARTICIPANTSTATUS_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.FINALGRADE ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FINALGRADE;
CREATE CACHED TABLE PUBLIC.MEETING(
                                      ID VARCHAR(255) NOT NULL,
                                      NAME VARCHAR(255),
                                      ONLYGROUPSPLIT BOOLEAN,
                                      SUBMISSIONWEIGHTING DECIMAL(19, 2),
                                      VERSION BIGINT,
                                      VISIBLE BOOLEAN,
                                      WISO BOOLEAN,
                                      YEAR TIMESTAMP
);
ALTER TABLE PUBLIC.MEETING ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEETING;
CREATE CACHED TABLE PUBLIC.PARTICIPANT(
                                          ID VARCHAR(255) NOT NULL,
                                          EMAIL VARCHAR(255),
                                          FIRSTNAME VARCHAR(255),
                                          LASTNAME VARCHAR(255),
                                          MATRIKELNR INTEGER,
                                          SEMESTER INTEGER,
                                          STATUS VARCHAR(255),
                                          VERSION BIGINT
);
ALTER TABLE PUBLIC.PARTICIPANT ADD CONSTRAINT PUBLIC.CONSTRAINT_AE PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPANT;
CREATE CACHED TABLE PUBLIC.PARTICIPANTSTATUS(
                                                ID VARCHAR(255) NOT NULL,
                                                MEETINGSTATUS INTEGER,
                                                VERSION BIGINT,
                                                GROUP_ID VARCHAR(255),
                                                MEETING_ID VARCHAR(255),
                                                PARTICIPANT_ID VARCHAR(255),
                                                TUTORIAL_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.PARTICIPANTSTATUS ADD CONSTRAINT PUBLIC.CONSTRAINT_6D PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPANTSTATUS;
CREATE CACHED TABLE PUBLIC.SUBMISSION(
                                         ID VARCHAR(255) NOT NULL,
                                         DATE TIMESTAMP,
                                         GROUPWORK BOOLEAN,
                                         MAXGRADE DECIMAL(19, 2),
                                         NAME VARCHAR(255),
                                         VERSION BIGINT,
                                         WEIGHTING DECIMAL(19, 2),
                                         MEETING_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.SUBMISSION ADD CONSTRAINT PUBLIC.CONSTRAINT_A1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUBMISSION;
CREATE CACHED TABLE PUBLIC.TASK(
                                   ID VARCHAR(255) NOT NULL,
                                   CRITERIA VARCHAR(255),
                                   DATE TIMESTAMP,
                                   NAME VARCHAR(255),
                                   NUMBER DOUBLE,
                                   POINTS DECIMAL(19, 2),
                                   WEIGHTING DECIMAL(19, 2),
                                   SUBMISSION_ID VARCHAR(255),
                                   TASK_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.TASK ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TASK;
CREATE CACHED TABLE PUBLIC.TGROUP(
                                     ID VARCHAR(255) NOT NULL,
                                     MAXPA INTEGER,
                                     NAME VARCHAR(255),
                                     NUMBER INTEGER,
                                     VERSION BIGINT,
                                     TUTORIAL_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.TGROUP ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TGROUP;
CREATE CACHED TABLE PUBLIC.TUTORIAL(
                                       ID VARCHAR(255) NOT NULL,
                                       DATE TIMESTAMP,
                                       INFO VARCHAR(255),
                                       NAME VARCHAR(255),
                                       VERSION BIGINT,
                                       MEETING_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.TUTORIAL ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TUTORIAL;
CREATE CACHED TABLE PUBLIC.USER(
                                   ID VARCHAR(255) NOT NULL,
                                   EMAIL VARCHAR(255),
                                   FIRSTNAME VARCHAR(255),
                                   LASTNAME VARCHAR(255),
                                   PASSWORD VARCHAR(255),
                                   ROLE INTEGER,
                                   STATUS BOOLEAN,
                                   VERSION BIGINT
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27E PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER;
INSERT INTO PUBLIC.USER(ID, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, ROLE, STATUS, VERSION) VALUES
('b0657f0d-3794-4039-bc43-084ec380b544', 'admin@uni-bremen.de', 'pass', 'pass', 'a2543046aee065007b7a6dd0fbb586da7832ff40fffa55d1a9977f68768907fa', 0, TRUE, 0);
CREATE CACHED TABLE PUBLIC.USERMEETINGROLE(
                                              ID VARCHAR(255) NOT NULL,
                                              ROLE INTEGER,
                                              VERSION BIGINT,
                                              MEETING_ID VARCHAR(255),
                                              USER_ID VARCHAR(255)
);
ALTER TABLE PUBLIC.USERMEETINGROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERMEETINGROLE;
CREATE CACHED TABLE PUBLIC.USERMEETINGROLE_TUTORIAL(
                                                       USERMEETINGROLES_ID VARCHAR(255) NOT NULL,
                                                       TUTORIALS_ID VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.USERMEETINGROLE_TUTORIAL ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(USERMEETINGROLES_ID, TUTORIALS_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERMEETINGROLE_TUTORIAL;
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_E6GKQUNXAJVYXL5UCTPL2VL2P UNIQUE(EMAIL);
ALTER TABLE PUBLIC.PARTICIPANTSTATUS ADD CONSTRAINT PUBLIC.FKKSYO8KPT7PDMAO0OEO37GE4GI FOREIGN KEY(PARTICIPANT_ID) REFERENCES PUBLIC.PARTICIPANT(ID) NOCHECK;
ALTER TABLE PUBLIC.FINALGRADE ADD CONSTRAINT PUBLIC.FK37CKX90DAAL258PT3P2MVPSY5 FOREIGN KEY(MEETING_ID) REFERENCES PUBLIC.MEETING(ID) NOCHECK;
ALTER TABLE PUBLIC.PARTICIPANTSTATUS ADD CONSTRAINT PUBLIC.FKOS9O85TPWU46H2NLXCFAIEWK7 FOREIGN KEY(GROUP_ID) REFERENCES PUBLIC.TGROUP(ID) NOCHECK;
ALTER TABLE PUBLIC.TGROUP ADD CONSTRAINT PUBLIC.FK1S0LYSIRCECFGOP3UF5SL20IQ FOREIGN KEY(TUTORIAL_ID) REFERENCES PUBLIC.TUTORIAL(ID) NOCHECK;
ALTER TABLE PUBLIC.EVALUATION ADD CONSTRAINT PUBLIC.FK1HMQLWCD46MN4DWY326EMVWE8 FOREIGN KEY(SUBMISSION_ID) REFERENCES PUBLIC.SUBMISSION(ID) NOCHECK;
ALTER TABLE PUBLIC.EVALUATION ADD CONSTRAINT PUBLIC.FKBOX4WM9LNAWIKD2C8TB2MVBKP FOREIGN KEY(PARTICIPANTSTATUS_ID) REFERENCES PUBLIC.PARTICIPANTSTATUS(ID) NOCHECK;
ALTER TABLE PUBLIC.TUTORIAL ADD CONSTRAINT PUBLIC.FKMRWR488THTNR8WN71QJI551T7 FOREIGN KEY(MEETING_ID) REFERENCES PUBLIC.MEETING(ID) NOCHECK;
ALTER TABLE PUBLIC.USERMEETINGROLE_TUTORIAL ADD CONSTRAINT PUBLIC.FK91T41PEYSQI8L5LCIBUNLK0BB FOREIGN KEY(USERMEETINGROLES_ID) REFERENCES PUBLIC.USERMEETINGROLE(ID) NOCHECK;
ALTER TABLE PUBLIC.EXAM ADD CONSTRAINT PUBLIC.FKSMQ7DC4XEHRCCGNMUAT875X7N FOREIGN KEY(MEETING_ID) REFERENCES PUBLIC.MEETING(ID) NOCHECK;
ALTER TABLE PUBLIC.USERMEETINGROLE ADD CONSTRAINT PUBLIC.FKG6P1JJK3AIGPEY6B4T865DFU1 FOREIGN KEY(MEETING_ID) REFERENCES PUBLIC.MEETING(ID) NOCHECK;
ALTER TABLE PUBLIC.USERMEETINGROLE ADD CONSTRAINT PUBLIC.FKJHMEHF9IEWV69AOBKSR3BVKN9 FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.FINALGRADE ADD CONSTRAINT PUBLIC.FKBPR9788XLMEI4MRVBBO4QVH08 FOREIGN KEY(PARTICIPANTSTATUS_ID) REFERENCES PUBLIC.PARTICIPANTSTATUS(ID) NOCHECK;
ALTER TABLE PUBLIC.PARTICIPANTSTATUS ADD CONSTRAINT PUBLIC.FKPEP03UNH0O6405P5WIVW0S63F FOREIGN KEY(TUTORIAL_ID) REFERENCES PUBLIC.TUTORIAL(ID) NOCHECK;
ALTER TABLE PUBLIC.SUBMISSION ADD CONSTRAINT PUBLIC.FK3A373L324EL1K382PWJ8AY07M FOREIGN KEY(MEETING_ID) REFERENCES PUBLIC.MEETING(ID) NOCHECK;
ALTER TABLE PUBLIC.TASK ADD CONSTRAINT PUBLIC.FKPALYWCUNO0F642KD66DMYXOK3 FOREIGN KEY(TASK_ID) REFERENCES PUBLIC.TASK(ID) NOCHECK;
ALTER TABLE PUBLIC.EVALUATION ADD CONSTRAINT PUBLIC.FKDFLU8KH6GDQVPHAL3XGFELIOX FOREIGN KEY(EXAM_ID) REFERENCES PUBLIC.EXAM(ID) NOCHECK;
ALTER TABLE PUBLIC.EVALUATION ADD CONSTRAINT PUBLIC.FKJYL9Q8H8GTAXVLYS3TTX2V7EN FOREIGN KEY(TASK_ID) REFERENCES PUBLIC.TASK(ID) NOCHECK;
ALTER TABLE PUBLIC.PARTICIPANTSTATUS ADD CONSTRAINT PUBLIC.FK76FHK987CD6MDCCX7F6TAB1C4 FOREIGN KEY(MEETING_ID) REFERENCES PUBLIC.MEETING(ID) NOCHECK;
ALTER TABLE PUBLIC.EVALUATION ADD CONSTRAINT PUBLIC.FK4969QRRVEQP1A8OBH7QFQ775Y FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.TASK ADD CONSTRAINT PUBLIC.FKH4TRQ1MUFK70HD6LP5ACX86G9 FOREIGN KEY(SUBMISSION_ID) REFERENCES PUBLIC.SUBMISSION(ID) NOCHECK;
ALTER TABLE PUBLIC.USERMEETINGROLE_TUTORIAL ADD CONSTRAINT PUBLIC.FKHRGLAA1RRJVDC3GLY1313SH2Y FOREIGN KEY(TUTORIALS_ID) REFERENCES PUBLIC.TUTORIAL(ID) NOCHECK;
